apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\kompose\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: cache-service
  name: cache-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: cache-service
status:
  loadBalancer: {}
