apiVersion: v1
kind: Service
metadata:
  labels:
    service: cache-service
  name: cache-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: cache-service
  type: LoadBalancer
