apiVersion: v1
kind: Pod
metadata:
  labels:
    service: cache-service
  name: cache-service
spec:
  containers:
  - env:
    - name: CACHE_MEM
      value: "256"
    - name: DATABASE_HOST
      value: mongo
    - name: DATABASE_NAME
      value: mydatabase
    - name: DATABASE_PORT
      value: "27017"
    - name: MQ_HOST
      value: rabbitmq
    - name: MQ_PORT
      value: "5672"
    - name: MQ_QUEUE
      value: events
    image: shubhamvrke/cache-service:1.0
    name: cache-service
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
