apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
      - env:
        - name: MONGO_DATA_DIR
          value: /data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: mongo:4.1
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
