database:
  host: "localhost"
  port: 27017
  username: ""
  password: ""
  name: "mydatabase"

cache:
  memory: 256

rabbit:
  host: "localhost"
  port: 5672
  username: ""
  password: ""
  queue: "events"

server:
  port: 8080
